"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="application-name" content="Surroo" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Surroo" />
        <meta
          name="description"
          content="Welcome to Surroo, your nimble personal assistant for organizing daily life with spirit and dynamism!"
        />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="msapplication-config" content="/icons/browserconfig.xml" />
        <meta name="msapplication-TileColor" content="#FFF" />
        <meta name="msapplication-tap-highlight" content="no" />
        <meta name="theme-color" content="#FFF" />

        <link rel="apple-touch-icon" href="/icons/touch-icon-iphone.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="/icons/152.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/icons/180.png" />
        <link rel="apple-touch-icon" sizes="167x167" href="/icons/167.png" />

        <link rel="icon" type="image/png" sizes="32x32" href="/icons/32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/icons/16.png" />
        <link rel="manifest" href="/manifest.json" />
        <link
          rel="mask-icon"
          href="/icons/safari-pinned-tab.svg"
          color="#5bbad5"
        />
        <link rel="shortcut icon" href="/favicon.ico" />

        <meta name="twitter:card" content="summary" />
        <meta name="twitter:url" content="https://surroo.vercel.app" />
        <meta name="twitter:title" content="Surroo" />
        <meta
          name="twitter:description"
          content="Welcome to Surroo, your nimble personal assistant for organizing daily life with spirit and dynamism!"
        />
        <meta
          name="twitter:image"
          content="https://surroo.vercel.app/icons/icon-192.png"
        />
        <meta name="twitter:creator" content="@Fede91" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Surroo" />
        <meta
          property="og:description"
          content="Welcome to Surroo, your nimble personal assistant for organizing daily life with spirit and dynamism!"
        />
        <meta property="og:site_name" content="Surroo" />
        <meta property="og:url" content="https://surroo.vercel.app" />
        <meta
          property="og:image"
          content="https://surroo.vercel.app/icons/512.png"
        />
      </head>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
